
@apiUrl = https://fw-teaching.fi/demo/wdbocms/api/v1/products


GET {{apiUrl}}

GET {{apiUrl}}/1002
Content-Type: application/json
{
    "name": "New Product",
    "description": "This is a new product.",
    "price": 19.99
}
